### ISSUE TITLE
关于 “离屏渲染(Offscreen rendering)” 的描述有误

### ISSUE THREAD

**Issue by chenyihu** [raozhizhen/JMRoundedCorner#1]
在这个场景下并非是 CPU 计算，性能问题的主要原因是由于离屏渲染需要使用昂贵的离屏缓存，以及做上下文切换导致（On-Screen, Off-Screen）的。 [Getting Pixels onto the Screen](https://www.objc.io/issues/3-views/moving-pixels-onto-the-screen/)

**Comment by raozhizhen** [comment]
非常感谢，我再查查看然后修改

2016年2月29日星期一，chenyihu notifications@github.com 写道：
