### ISSUE TITLE
设置了背景色的情况下，就没有效果了

### ISSUE THREAD

**Issue by cqzhlei** [raozhizhen/JMRoundedCorner#10]
<img width="1050" alt="2016-05-30 15 19 24" src="https://cloud.githubusercontent.com/assets/8794512/15642451/05d78f38-267a-11e6-9406-971fd8452041.png">
写了第47行代码，就无法裁边了。我找了很久，才找到这个原因。。。。。。。
建议楼主特别注明一下吧，不然很容易踩这个坑的。。。。

**Comment by raozhizhen** [comment]
恩恩，好的，不过如果不是4个圆角不同，且没有 image 需要裁剪的话，可以直接 
label.layer.cornerRadius = 7;
label.layer.backgroundColor = [UIColor whiteColor].CGColor;
    label.layer.borderColor = [UIColor redColor].CGColor;
    label.layer.borderWidth = 2;
这样也不会造成离屏渲染

**Comment by Vienta** [comment]
@cqzhlei @raozhizhen 不过这种情况下失效说明封装的也不是很好

**Comment by raozhizhen** [comment]
@Vienta 嗯，主要是想使用的时候方便点，所以在 layer 层做的操作，所以背景颜色会覆盖 layer 层上的效果
