### ISSUE TITLE
主线程卡死

### ISSUE THREAD

**Issue by hydyy** [raozhizhen/JMRoundedCorner#11]
退出后台，进入前台，然后执行 jm_setJMRadius。。。

这句话会导致整个界面卡死 ， 很严重
dispatch_sync(dispatch_get_main_queue(), ^{
            _size = wself.bounds.size;
        });

**Comment by raozhizhen** [comment]
这是很严重的BUG啊，非常严重，非常抱歉我没有测试出来，我仔细研究一下

**Comment by raozhizhen** [comment]
@hydyy 我这没有复现，方便加QQ聊一下具体出现场景吗？337519524.

**Comment by gdfyj90** [comment]
dispatch_sync(dispatch_get_main_queue(), ^{

});
这句话本身就是死锁吧，是async

**Comment by raozhizhen** [comment]
@gdfyj90 我阻塞的非主线程，这行代码的意思是将 block 里的任务添加到主线程，并阻塞当前线程，然后等主线程执行了 block 里的任务，就会继续执行当前线程。你可以断点试试，很有趣的

**Comment by hydyy** [comment]
小技巧很危险，边界情况无法测试 。 我感觉我遇到的是很特殊的情况，但是一旦遇到就是毁灭。是不是应该考虑下？

发自我的 iPhone

**Comment by raozhizhen** [comment]
@hydyy 嗯，我再想想有没有更好的实现方法
