### ISSUE TITLE
contentText 是nil。

### ISSUE THREAD

**Issue by ARonDellon** [raozhizhen/JMRoundedCorner#12]
![qq20160612-0](https://cloud.githubusercontent.com/assets/9428073/15990147/716b6b0a-30bd-11e6-9908-6b9c62074d16.png)

如图

**Comment by ARonDellon** [comment]
是不是要在drawRect里写

**Comment by raozhizhen** [comment]
这是 Xcode-7 的 BUG。https://forums.developer.apple.com/thread/13683

**Comment by raozhizhen** [comment]
不影响使用，使用上有其它问题吗

**Comment by ARonDellon** [comment]
使用没有问题。 thx。我去手动消除警告。
