### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by icharlie2014** [raozhizhen/JMRoundedCorner#14]
[self.view jm_setJMRadius:JMRadiusMake(0, 10, 0, 10) withBackgroundColor:[UIColor colorWithRed:0.918 green:0.533 blue:0.463 alpha:1.000]];

上面的代码

view 不释放

**Comment by raozhizhen** [comment]
好的 我会检查检查 谢谢你的反馈

**Comment by raozhizhen** [comment]
@icharlie2014 我测试了一下。view 会正常释放，可以给我提供更详细的代码吗？以及具体的现象。
如果只是单纯的内存增加的话，你可以试试点击 home 键，再返回应用看看内存是否会下降

**Comment by callmewenxi** [comment]
内存持续增长,这个不太好啊 =.=

**Comment by raozhizhen** [comment]
@callmewenxi 其实内存的绘制缓存
你要是点击 home 键 内存又会正确释放掉
不算内存泄露吧
