### ISSUE TITLE
各种告警错误

### ISSUE THREAD

**Issue by xclidongbo** [raozhizhen/JMRoundedCorner#17]
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextSetLineWidth: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextMoveToPoint: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextAddArcToPoint: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextAddArcToPoint: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextAddArcToPoint: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextAddArcToPoint: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 13 16:53:16  iphoneLive[4177] <Error>: CGContextDrawPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by xclidongbo** [comment]
xcode的bug?

**Comment by raozhizhen** [comment]
@xclidongbo  maybe 我也没找到原因 只找到这个-> https://forums.developer.apple.com/thread/13683
