### ISSUE TITLE
关于图片本身就是圆角的问题

### ISSUE THREAD

**Issue by sunjianan** [raozhizhen/JMRoundedCorner#19]
如果图片本身就是圆角，裁剪之后会出现黑线
![image](https://cloud.githubusercontent.com/assets/4962314/21599600/4193bf34-d1aa-11e6-8e44-8d5cc9641bfe.png)

**Comment by raozhizhen** [comment]
谢谢 我会看看这个问题的@sunjianan

**Comment by raozhizhen** [comment]
@sunjianan 将 UIImage+JMRadius.h 文件里的 - (UIImage *)scaleToSize:(CGSize)size withContentMode:(UIViewContentMode)contentMode backgroundColor:(UIColor *)backgroundColor 方法里的     CGContextDrawPath(context, kCGPathFillStroke);
 改成      CGContextDrawPath(context, kCGPathFill);
你先这样改吧，我后续版本再发布

**Comment by raozhizhen** [comment]
@sunjianan 或者 pod 'JMRoundedCorner', :git => 'https://github.com/raozhizhen/JMRoundedCorner.git', :tag => '1.9.2'

**Comment by sunjianan** [comment]
@raozhizhen  你的库是依赖自己重构的YYWebImage，如果工程里本身有YYKit的话这样会导致冲突，所以是不是可以在原生YYWebImage的基础上做扩展或者换个命名？

**Comment by raozhizhen** [comment]
@sunjianan 其实不建议你集成 YYKit，耀源把他们拆分了，你拆开来集成吧， YYKit 的代码都没有拆开来的代码维护的勤快。
