### ISSUE TITLE
建议方法名增加前缀

### ISSUE THREAD

**Issue by klaus01** [raozhizhen/JMRoundedCorner#3]
如rc_setCornerRadius

**Comment by raozhizhen** [comment]
感觉不加调用起来舒服点，所以在UIView的分类里没有添加，其实和别人的代码起冲突的概率也不大，让我纠结一下

**Comment by klaus01** [comment]
前缀还有个好处是：新人在维护已使用该库的代码时，看到带前缀的方法名基本反应都是该方法是第三方库的，从而查看库说明了解代码得更快。这也间接为库带来更多用户。

从长远的角度出发，加前缀来避免方法名重复是很有必要的。

**Comment by raozhizhen** [comment]
受教了  谢谢
