### ISSUE TITLE
无法裁剪背景色

### ISSUE THREAD

**Issue by CodeY2J** [raozhizhen/JMRoundedCorner#4]
如果我UIView或者UIButton设置了背景色,`[view setBackgroundColor:[UIColor blueColor]]`,这样圆角之后，底色还是背景色。

**Comment by raozhizhen** [comment]
- (void)setCornerRadius:(CGFloat)radius withBorderColor:(UIColor *)borderColor borderWidth:(CGFloat)borderWidth backgroundColor:(UIColor *)backgroundColor backgroundImage:(UIImage *)backgroundImage ContentMode:(UIViewContentMode)contentMode;
  需要把背景颜色也传进去一起裁剪。调用这个方法，bordcolor 和 boardwidth可以传ni和0

**Comment by CodeY2J** [comment]
![img](http://img.hoop8.com/attachments/1603/3801760341837.png) 依然不行。。背景我用设的红色，然后调用`(void)setCornerRadius:(CGFloat)radius withBorderColor:(UIColor *)borderColor borderWidth:(CGFloat)borderWidth backgroundColor:(UIColor *)backgroundColor backgroundImage:(UIImage *)backgroundImage ContentMode:(UIViewContentMode)contentMode;` 依然还是这样。。。

**Comment by raozhizhen** [comment]
[view setBackgroundColor:[UIColor redColor]]这行代码删除了嘛  如果删除了还是这个样子的话 你留个QQ我加你一起看看
