### ISSUE TITLE
循环引用问题

### ISSUE THREAD

**Issue by hydyy** [raozhizhen/JMRoundedCorner#9]
- (void)jm_setJMRadius:(JMRadius)radius withBorderColor:(UIColor *)borderColor borderWidth:(CGFloat)borderWidth backgroundColor:(UIColor *)backgroundColor backgroundImage:(UIImage *)backgroundImage contentMode:(UIViewContentMode)contentMode size:(CGSize)size

这个方法中在block中嵌套了block， 内存会出问题。 

检查下吧

**Comment by raozhizhen** [comment]
恩恩 好的，非常感谢
